# Generated by Django 6.0.5 on 2026-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('task', 'Task'), ('workspace', 'Workspace'), ('security', 'Security'), ('task_assigned', 'Task assigned'), ('due_reminder', 'Due reminder'), ('comment_added', 'Comment added'), ('workspace_invite', 'Workspace invite'), ('task_completed', 'Task completed')], default='info', max_length=30),
        ),
    ]
