# Generated by Django 6.0.5 on 2026-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='color',
            field=models.CharField(default='#2563eb', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
